services:
      frontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        volumes:
          - ./frontend/dist:/app/dist  # Valid volume mapping
        command: ["npm", "run", "build"]
        depends_on:
          - backend

      backend:
        build:
          context: ./backend
          dockerfile: Dockerfile
        ports:
          - "5000:5000"  
        environment:
         - MONGO_URI=mongodb://db:27017
        depends_on:
          - db

      db:
        build:
          context: ./database
          dockerfile: Dockerfile

        ports:
          - "27017:27017"
        volumes:
          - db-data:/data/db
          - ./database/init:/docker-entrypoint-initdb.d


      nginx:
        image: nginx:alpine
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
          - ./frontend/dist:/usr/share/nginx/html  # Serve frontend files (Ensure frontendPath is correct)
          
        ports:
          - "8080:80"  # Expose Nginx on port 8080
        depends_on:
          - backend
          - frontend # Add frontend only if it exists
          - db

networks:
  app-network:
    driver: bridge

volumes:
  db-data: